import { Component } from '@angular/core';
import { NgFor } from '@angular/common';

@Component({
  selector: 'app-board',
  standalone: true,
  imports: [NgFor],
  templateUrl: './board.component.html',
  styleUrl: './board.component.scss'
})
export class BoardComponent {
  pixels: string[] = Array.from({ length: 50 * 50 }).map(() => colors[Math.floor(Math.random() * colors.length)]);
  get matrixOrder() {
    return Math.sqrt(this.pixels.length);
  }
  handleClick(i: number): void {
    this.pixels[i] = "black";
  }
}

const colors = [
  "indianred",
  "lightcoral",
  "salmon",
  "darksalmon",
  "lightsalmon",
  "crimson",
  "red",
  "firebrick",
  "darkred",
  "maroon",
  "pink",
  "lightpink",
  "hotpink",
  "deeppink",
  "mediumvioletred",
  "palevioletred",
  "coral",
  "tomato",
  "orangered",
  "darkorange",
  "orange",
  "gold",
  "yellow",
  "lightyellow",
  "lemonchiffon",
  "lightgoldenrodyellow",
  "papayawhip",
  "moccasin",
  "peachpuff",
  "palegoldenrod",
  "khaki",
  "darkkhaki",
  "lavender",
  "thistle",
  "plum",
  "violet",
  "orchid",
  "fuchsia",
  "magenta",
  "mediumorchid",
  "mediumpurple",
  "blueviolet",
  "darkviolet",
  "darkorchid",
  "darkmagenta",
  "purple",
  "indigo",
  "slateblue",
  "darkslateblue",
  "greenyellow",
  "chartreuse",
  "lawngreen",
  "lime",
  "limegreen",
  "palegreen",
  "lightgreen",
  "mediumspringgreen",
  "springgreen",
  "mediumseagreen",
  "seagreen",
  "forestgreen",
  "green",
  "darkgreen",
  "yellowgreen",
  "olivedrab",
  "olive",
  "darkolivegreen",
  "mediumaquamarine",
  "darkseagreen",
  "lightseagreen",
  "darkcyan",
  "teal",
  "aqua",
  "cyan",
  "lightcyan",
  "paleturquoise",
  "aquamarine",
  "turquoise",
  "mediumturquoise",
  "darkturquoise",
  "cadetblue",
  "steelblue",
  "lightsteelblue",
  "powderblue",
  "lightblue",
  "skyblue",
  "lightskyblue",
  "deepskyblue",
  "dodgerblue",
  "cornflowerblue",
  "mediumslateblue",
  "royalblue",
  "blue",
  "mediumblue",
  "darkblue",
  "navy",
  "midnightblue",
  "cornsilk",
  "blanchedalmond",
  "bisque",
  "navajowhite",
  "wheat",
  "burlywood",
  "tan",
  "rosybrown",
  "sandybrown",
  "goldenrod",
  "darkgoldenrod",
  "peru",
  "chocolate",
  "saddlebrown",
  "sienna",
  "brown",
  "white",
  "snow",
  "honeydew",
  "mintcream",
  "azure",
  "aliceblue",
  "ghostwhite",
  "whitesmoke",
  "seashell",
  "beige",
  "oldlace",
  "floralwhite",
  "ivory",
  "antiquewhite",
  "linen",
  "lavenderblush",
  "mistyrose",
  "gainsboro",
  "lightgrey",
  "silver",
  "darkgray",
  "gray",
  "dimgray",
  "lightslategray",
  "slategray",
  "darkslategray",
  "black"
]